[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
vault = "BfbSEiML6f23QyDjsFjUBUCnAHXFSq9Hmtg2nSLdXP3N"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/Desktop/turbin3/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
